### ISSUE TITLE
Hi! Welcome to GitHub!

### ISSUE THREAD

**Issue by alexkdeveloper** [dida-code/lettreplacer#1]
I like the way you start. I invite you to get acquainted with my creations.
Sorry, but mostly I write in Vala.

My projects:
https://github.com/alexkdeveloper?tab=repositories

**Comment by alexkdeveloper** [comment]
I have a small python project:
https://github.com/alexkdeveloper/zodiac

**Comment by alexkdeveloper** [comment]
I will be very grateful if you help me in developing these small projects.

**Comment by dida-code** [comment]
Hello Alexey,glad you reached out to me but I'm an absolute beginner in developing python apps. If you have a specific question and if I can solve it, I would be happy to help you

**Comment by alexkdeveloper** [comment]
I respect and admire medical professionals. It is thanks to your work that many of us are still alive..

And in any case, I want to help you in mastering python - this truly universal programming language.

Some of my developments are quite simple, and they are done in python.

The same [Zodiac](https://github.com/alexkdeveloper/zodiac) - it wouldn't exist without Python. Thanks to this powerful language, it is possible not only to calculate the coordinates of planets, but also to engage in artificial intelligence.

To do this, you can explore the following repositories:
https://github.com/alexkdeveloper/baichat

It's a pretty simple application, and it's written in python

GTK4 is used as the graphical interface . 
You'll get used to it quickly. There is nothing complicated there)))

I write my programs using GTK 4 + libadwaita.

And I also want to say that if you have any questions, you can always contact me.  I'll try to help you.

**Comment by dida-code** [comment]
Thank you very much, I really appreciate what you wrote. I will definitely try your applications... I'm learning gtk3 because it's still complicated for me to create ui files manually, I'm using glade for that.

**Comment by alexkdeveloper** [comment]
I advise you to use [Cambalache](https://flathub.org/ru/apps/ar.xjuan.Cambalache) for UI development. You can use it to create interfaces on GTK4.

**Comment by alexkdeveloper** [comment]
You can also use [Blueprint](https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/) to create a user interface.

**Comment by dida-code** [comment]
I tried your app "zodiac", it works great, has a clean look and is very fluid... I just don't understand astrology :)
Great works.
Did you use "[Cambalache](https://gitlab.gnome.org/jpu/cambalache)" for window.ui?
I have tried to open window.ui from gnome builder with "[Cambalache](https://gitlab.gnome.org/jpu/cambalache)" and i got error "Either target_tk or filename are required". when i change name to window.ui.cmb, it is same error...

**Comment by alexkdeveloper** [comment]
In Cambalache, it is better to create an interface file from scratch. The program has certain problems with opening files. Sometimes the interface is not displayed at all, although the component tree on the left panel is displayed quite correctly. I really hope that the developers will solve these problems soon.

**Comment by dida-code** [comment]
ok, thanks for advice.
I have one more question, sorry if i'm boring, i'm interested in adding an app to flathub. specifically for this application that I made, I submitted PR, nothing happened for 10 days except i got a test version i tried it and it works. I closed that PR and opened a new one following all the steps in the flathub docs. Can you take a look when you have time if everything is ok and if not, what should i do (https://github.com/flathub/flathub/pull/4511).
Again, sorry if i'm boring.

**Comment by alexkdeveloper** [comment]
It seems to me that there are too many files in your request. It is enough to specify only the manifest. 

Also, if the application does not need Internet access, it is better to exclude this permission from the manifest. 

In the sources section, the reviewer may ask to specify a commit.

**Comment by dida-code** [comment]
Thank you, I turned off the permission to access the Internet, and as for PR, I only added the manifest and everything else was added automatically. I will wait for one of the administrators to contact me...

**Comment by alexkdeveloper** [comment]
As far as I know, the test builds of the application are executed according to the manifest contained in the request.

The manifest in the program repository is not taken into account when building for Flathub. 

Therefore, all changes, for example, regarding the use of various permissions, must be made in the manifest located in the add request.

**Comment by dida-code** [comment]
Thanks for the previous reply.
I have start new project with gtk4 and cambalanche. It is some Quiz app. I have problem with import json file.
when i putt locall path it work:
res = '/home/mint/Projects/test/src/example.json'
        with open (res, 'r') as f:
            data = json.load(f)
            print(data)
But when i put resource path, it gives me an error:
res = Gio.resources_lookup_data('/com/dida/test/example.json', Gio.ResourceLookupFlags.NONE)
        with open (res, 'r') as f:
            data = json.load(f)
            print(data)
TypeError: expected str, bytes or os.PathLike object, not Bytes
what should I do?

**Comment by alexkdeveloper** [comment]
Why do you need to apply open to res. The resource is already contained in the variable in the form of Bytes. You need to cast this type to a string.

You can use the get_data method in combination with decode.

See the examples here:
https://programtalk.com/python-examples/gi.repository.Gio.resources_lookup_data/

**Comment by dida-code** [comment]
I did it:
bytes = Gio.resources_lookup_data('/com/dida/test/example.json', 0)
        res=(bytes.get_data().decode('utf-8'))
        print(res)
I tried to find a solution but I didn't succeed. It means a lot to me that you help me. There are few people today who would help a complete stranger.

**Comment by alexkdeveloper** [comment]
This is strange. 
The code should work. Are the resources registered in a special file? 
In turn, the file must be registered in the build script. 
What template do you use for the app? 
I would recommend using GNOME Builder. Everything is ready for development.

**Comment by dida-code** [comment]
I use GNOME Builder, the code work...
I didn't write well. I wanted to say that I've been looking for a solution for a long time and I couldn't find it and it was so simple...

**Comment by alexkdeveloper** [comment]
I would like to touch on the topic of Cambalache once again.

I didn't use it when creating Zodiac. I took most of the markup code from my other application (Astronum). 

But recently I decided to open the program interface via Cambalache. And it didn't open. Although the hierarchy of components on the sidebar, as I said in one of the previous messages, is displayed correctly. The .cmb file is not created automatically, and you have to create it by clicking on the save button. Then, if you open the cmb file, the interface will display quite normally.  

And so the program is quite suitable for designing interfaces. It's not without its drawbacks, but you can take advantage of it.

**Comment by dida-code** [comment]
When you told me about cambalanche, i started doing a little research and i figured out how it works. I create a ui file using cambalache and then transfer it to GNOME Builder and make a small correction in the code. I change "object" to "template" and then it works.
I like Glade better because every design change I just reload directly into Builder.
I started a new project and I'm working on it using cambalanche and so far I'm getting the hang of it but I still have a lot to learn

**Comment by alexkdeveloper** [comment]
Are you using libadwaita in your new project?

**Comment by dida-code** [comment]
I haven't tried it, just gtk elements
