### ISSUE TITLE
Glad to see you back on Github!!!

### ISSUE THREAD

**Issue by alexkdeveloper** [dida-code/lettreplacer#2]
Where have you been for so long?

I see that your application can be translated to GTK4 + Libadwaita.
What do you think about this?

**Comment by alexkdeveloper** [comment]
When translating, the greatest difficulties are expected when translating the application interface file.

**Comment by alexkdeveloper** [comment]
The interface can be recreated using Cambalache. I do not yet know the tools that will allow me to turn old versions of the interface into new ones.

**Comment by dida-code** [comment]
Hello after a long time, I was absent for a long time due to many obligations... I started this application in gt3 and updated it in gt3. I will certainly try to translate it to gt4 as soon as time permits

**Comment by dida-code** [comment]
I will have to do the interface in Cambalache from the very beginning and just add the existing functions. By the way, this application is exclusively for the Serbian alphabet, so I don't believe that many people will use it. I personally use it when I process some texts, so it means a lot to me because it speeds up the process itself.

**Comment by alexkdeveloper** [comment]
Yes, indeed, I noticed that this is a rather specific application and it does not work for some languages.

But nevertheless, as always, I sincerely offer my help.

**Comment by dida-code** [comment]
Thanks a lot.
I have more ideas, I just don't have time to devote myself.

**Comment by dida-code** [comment]
Hey Alex, 
can i ask you for a favor when you have time, i actually updated the lettreplacer app and now when i clone the main repository in gnome builder, gnome builder won't start the application, it gives me an error: Application started at 01:49:00 PM
bwrap: execvp lettreplacer: No such file or directory
Application exited
but when I download lettreplacer-main in zip format and run it in gnome builder, the application works
it's the same code, I don't know why it's giving me an error...
when i rename the folder, any name, the app works

**Comment by alexkdeveloper** [comment]
Hi.

Perhaps you have changed something in the build scripts?

Alternatively, you can try clearing the development environment cache.

If I remember correctly, he is on this path:

/home/user-name/.var/app/org.gnome.Builder/cache/gnome-builder/projects

**Comment by dida-code** [comment]
Thank you for the tips, i tried but always the same error, i even tried on another system... thank you anyway
